import os
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors

def generate_incident_pdf(incidents, output_path):
    # Setup document geometry
    doc = SimpleDocTemplate(
        output_path, 
        pagesize=letter, 
        rightMargin=30, 
        leftMargin=30, 
        topMargin=30, 
        bottomMargin=30
    )
    elements = []
    styles = getSampleStyleSheet()
    
    # Custom styling
    title_style = ParagraphStyle(
        'TitleStyle',
        parent=styles['Heading1'],
        fontSize=18,
        textColor=colors.HexColor('#0f172a'),
        spaceAfter=4
    )
    
    subtitle_style = ParagraphStyle(
        'SubTitleStyle',
        parent=styles['Normal'],
        fontSize=9,
        textColor=colors.HexColor('#64748b'),
        spaceAfter=15
    )

    # NEW: Specific style for the long text in the insight column
    insight_style = ParagraphStyle(
        'InsightStyle',
        parent=styles['Normal'],
        fontSize=8,
        textColor=colors.HexColor('#0f172a'),
        alignment=0, # 0 = Left aligned for better readability on long text
        leading=10 # Line spacing
    )
    
    elements.append(Paragraph("CyberScope-AI: Security Compliance Report", title_style))
    elements.append(Paragraph("Official export generated by Security Operations Center (SOC) Engine", subtitle_style))
    elements.append(Spacer(1, 10))
    
    # Table Header and Rows
    data = [["ID", "Source Sensor", "Temp ( C)", "Volt (V)", "Timestamp", "AI Threat Insight"]]
    
    # Reverse to show newest incidents first
    for inc in incidents[::-1]:
        data.append([
            f"INC-00{inc[0]}",
            str(inc[1]),
            f"{inc[2]} C",
            f"{inc[3]} V",
            str(inc[4]).replace('T', ' ')[:19],
            # Wrap the long text in a Paragraph object so it wraps to the next line
            Paragraph(str(inc[5]), insight_style) 
        ])
        
    # Build Table Layout
    t = Table(data, colWidths=[50, 65, 55, 50, 115, 205])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#1e293b')),
        ('TEXTCOLOR', (0,0), (-1,0), colors.whitesmoke),
        ('ALIGN', (0,0), (-1,-1), 'CENTER'),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTSIZE', (0,0), (-1,0), 8),
        ('BOTTOMPADDING', (0,0), (-1,0), 6),
        ('TOPPADDING', (0,0), (-1,0), 6),
        ('BACKGROUND', (0,1), (-1,-1), colors.HexColor('#f8fafc')),
        ('TEXTCOLOR', (0,1), (-1,-1), colors.HexColor('#0f172a')),
        ('FONTNAME', (0,1), (-1,-1), 'Helvetica'),
        ('FONTSIZE', (0,1), (-1,-1), 8),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#cbd5e1')),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
    ]))
    
    elements.append(t)
    doc.build(elements)